version: '3'

services:
  reaction:
    image: reactioncommerce/reaction:latest
    ports:
      - "3000:3000"
    environment:
      - ROOT_URL=http://localhost:3000
      - MONGO_URL=mongodb://mongo:27017/reaction
      - STORE_URL=http://localhost:4000
    depends_on:
      - mongo
    networks:
      - net

  mongo:
    image: mongo
    volumes:
      - ./mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - net
networks:
  net: