version: '3'

services:
  web:
    image: joomla
    ports:
      - "80:80"
    volumes:
      - ./joomla:/var/www/html
    environment:
      - JOOMLA_DB_HOST=db
      - JOOMLA_DB_USER=joomla
      - JOOMLA_DB_PASSWORD=joomla
      - JOOMLA_DB_NAME=joomla
    depends_on:
      - db
  db:
    image: mysql:5.7
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=joomla
      - MYSQL_USER=joomla
      - MYSQL_PASSWORD=joomla
      